### ISSUE TITLE
[bug] getting a database error on manual update

### ISSUE THREAD

**Issue by xtj-9182** [raulhaag/MiMangaNu#261]
so I just did a manual update and now I'm getting this:
`
05-11 19:29:03.521 32006-1012/ar.rulosoft.mimanganu E/SQLiteDatabase: Error inserting extra=null estado=-1 manga_id=56 nombre=Prison School Chapter 214 paginas=0 leidas=0 path=/Manga/Prison-School/Chapter-214?id=273227
                                                                      android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: capitulos.path (code 2067)
                                                                          at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                                          at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
                                                                          at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                                                                          at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                                          at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
                                                                          at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
                                                                          at ar.rulosoft.mimanganu.componentes.Database.addChapter(Database.java:196)
                                                                          at ar.rulosoft.mimanganu.servers.ServerBase.searchForNewChapters(ServerBase.java:214)
                                                                          at ar.rulosoft.mimanganu.MainFragment$UpdateListTask$1.run(MainFragment.java:526)
                                                                          at java.lang.Thread.run(Thread.java:818)`

did I shoot my db somehow? I was doing lots of crash testing recently so I tried to break the app...

**Comment by raulhaag** [comment]
i don't know if you already have the chapter 214 on the your list ¿It's there?

**Comment by xtj-9182** [comment]
in the app it's only showing cha. 213 and if I remove that then it's still happening ... 

tomorrow I try to look inside the db programmatically

**Comment by xtj-9182** [comment]
as it turns out I somehow had ch. 214 in my db with mangaId = -1. Interestingly we already have a function to remove orphaned chapters like that but we didn't use it lol.

Anyway I fixed it by making the places where we addChapters more robust so when we fail with an SQLiteConstraintException again we will now try to removeOrphanedchapters to possibly fix it, this worked for me and it could also fix problems for others woohoo.
