### ISSUE TITLE
Can't add manga "from folder"

### ISSUE THREAD

**Issue by blastrock** [raulhaag/MiMangaNu#510]
It fails with a database error. Here is the logcat:

```
01-18 23:23:56.231 27623 16214 E Database: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: manga.autor (code 1299)
01-18 23:23:56.231 27623 16214 E Database: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
01-18 23:23:56.231 27623 16214 E Database: 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
01-18 23:23:56.231 27623 16214 E Database: 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
01-18 23:23:56.231 27623 16214 E Database: 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
01-18 23:23:56.231 27623 16214 E Database: 	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1499)
01-18 23:23:56.231 27623 16214 E Database: 	at android.database.sqlite.SQLiteDatabase.insertOrThrow(SQLiteDatabase.java:1394)
01-18 23:23:56.231 27623 16214 E Database: 	at ar.rulosoft.mimanganu.componentes.Database.addManga(Database.java:156)
01-18 23:23:56.231 27623 16214 E Database: 	at ar.rulosoft.mimanganu.componentes.MangaFolderSelect$AddMangaTask.doInBackground(MangaFolderSelect.java:155)
01-18 23:23:56.231 27623 16214 E Database: 	at ar.rulosoft.mimanganu.componentes.MangaFolderSelect$AddMangaTask.doInBackground(MangaFolderSelect.java:120)
01-18 23:23:56.231 27623 16214 E Database: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
01-18 23:23:56.231 27623 16214 E Database: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-18 23:23:56.231 27623 16214 E Database: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
01-18 23:23:56.231 27623 16214 E Database: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
01-18 23:23:56.231 27623 16214 E Database: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
01-18 23:23:56.231 27623 16214 E Database: 	at java.lang.Thread.run(Thread.java:764)
```

I just chose a plain folder to import, do the folder need to be in a specific format?

**Comment by raulhaag** [comment]
i fix this on last commit, this sunday if i have time i go to publish a new version

**Comment by raulhaag** [comment]
about the format, it a master folder (if contain cover.jpg is used on preview) with a collection of "chapters folders" with the images on those

**Comment by blastrock** [comment]
It works with the last version, thanks!
